### ISSUE TITLE
Clearer API Keys Source

### ISSUE THREAD

**Issue by afonsojramos** [algolia/algoliasearch-crawler-github-actions#201]
I've managed to find all the required keys (or so I thought), however, even after finding all the necessary keys it seems that they are still wrong?

Check this action: https://github.com/spicetify/spicetify-docs/runs/5978167459?check_suite_focus=true

As such, I would recommend to add a clarification to which API keys to use and where to get them so that everyone can quickly and painlessly use this action.

**Comment by bodinsamuel** [comment]
Hey, sorry about that this Github Actions lacks a proper tutorial.
Algolia Crawler credentials are found here:
https://crawler.algolia.com/admin/user/settings/
```
crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
``` 

--- 

Algolia credentials are found here:
https://www.algolia.com/account/api-keys/all
```
algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
```

**Comment by afonsojramos** [comment]
Working! But my action is still failing, can you give some help here? 

https://github.com/spicetify/spicetify-docs/runs/6025064795?check_suite_focus=true

**Comment by bodinsamuel** [comment]
Github actions is a bit weird in the way it presents the error, the actual message is https://github.com/spicetify/spicetify-docs/actions/runs/2167598318
`The given API key is missing some permissions: addObject` seems like you did not used the right one.
You can copy the apiKey in the crawler you already have or create a new one that have 

```  'search','addObject','deleteObject','deleteIndex','settings','editSettings', 'listIndexes',```

**Comment by afonsojramos** [comment]
Okay, so update on this 😪 It seems that open source projects with Algolia do not have an API Key with these permissions nor do they have access to any admin API Key so I could create a new key that enables that... I will contact support on this.

**Comment by shortcuts** [comment]
Hey @afonsojramos, you can use the api key in your crawler config, which have the expected rights to run the GitHub action. You can find it at the bottom of the editor: https://crawler.algolia.com/admin/crawlers/21cd96e7-6b93-46d4-9d67-ca808f1c8750/configuration/edit

**Comment by afonsojramos** [comment]
It seems that I crossed a hurdle indeed, thanks @shortcuts! 

Afterwards, however, I got the error `The given API key doesn't have access to the required indexes (crawler_*)`. But it was fixed by adding the `crawler-name` property. It was a bit counter intuitive that in this case index = crawler. But I will close this issue now, thanks!
